spring:
  application:
    name: "security"
  security:
    user:
      name: oussama
      password: oussama
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3307/users
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: prod
logging:
  level:
    org:
      springframework:
        security:
          ERROR
